-- Dulce Maria Reposteria — Ventas (MVP)
-- Ejecutar en phpPgAdmin en la DB: hernanci_dulcemaria

CREATE TABLE IF NOT EXISTS customers (
  id UUID PRIMARY KEY,
  email TEXT UNIQUE,
  full_name TEXT NOT NULL,
  phone TEXT,
  address TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY,
  order_no BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  customer_id UUID NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,

  status TEXT NOT NULL DEFAULT 'DELIVERED'
    CHECK (status IN ('PENDING_CONFIRMATION','CONFIRMED','PREPARING','READY','DELIVERED','CANCELLED')),

  payment_status TEXT NOT NULL DEFAULT 'PAID'
    CHECK (payment_status IN ('PENDING','PAID','FAILED','REFUNDED')),

  payment_method TEXT NOT NULL DEFAULT 'CASH'
    CHECK (payment_method IN ('TRANSFER','CASH','ONLINE')),

  delivery_method TEXT NOT NULL DEFAULT 'PICKUP'
    CHECK (delivery_method IN ('PICKUP','DELIVERY')),

  subtotal_clp INT NOT NULL DEFAULT 0,
  delivery_fee_clp INT NOT NULL DEFAULT 0,
  total_clp INT NOT NULL DEFAULT 0,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);

CREATE TABLE IF NOT EXISTS order_items (
  id UUID PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,

  product_name_snapshot TEXT NOT NULL,
  unit_price_clp INT NOT NULL,
  qty INT NOT NULL CHECK (qty > 0),
  line_total_clp INT NOT NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product ON order_items(product_id);
