/**
 * Complete Database Migration (Canonical Schema)
 * 
 * Ejecuta migraciones completas e idempotentes para:
 * - Crear todas las tablas si no existen
 * - Agregar columnas faltantes
 * - Crear índices
 * - Crear triggers updated_at
 * - Fix UNIQUE constraint en customers.email
 * 
 * Compatible con PostgreSQL 10.23
 * Seguro ejecutar múltiples veces (idempotente)
 */

const { getPool } = require("../db");

async function runCompleteMigrations() {
  const pool = getPool();
  const client = await pool.connect();

  console.log("🔄 Starting complete database migration...");

  const statements = [
    // Set search path
    `SET search_path TO public;`,

    // ============================================
    // TABLAS BASE
    // ============================================

    // Tabla: users
    `CREATE TABLE IF NOT EXISTS users (
      id UUID PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      full_name TEXT,
      role TEXT NOT NULL DEFAULT 'STAFF' CHECK (role IN ('SUPERADMIN','ADMIN','STAFF')),
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,

    // Tabla: products
    `CREATE TABLE IF NOT EXISTS products (
      id UUID PRIMARY KEY,
      name TEXT NOT NULL,
      slug TEXT NOT NULL UNIQUE,
      description TEXT,
      price_clp INT NOT NULL CHECK (price_clp >= 0),
      stock_qty INT NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,

    // Tabla: customers
    `CREATE TABLE IF NOT EXISTS customers (
      id UUID PRIMARY KEY,
      email TEXT,
      full_name TEXT NOT NULL,
      phone TEXT,
      address TEXT,
      notes TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,

    // Tabla: orders
    `CREATE TABLE IF NOT EXISTS orders (
      id UUID PRIMARY KEY,
      order_no BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
      customer_id UUID NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
      
      status TEXT NOT NULL DEFAULT 'DELIVERED'
        CHECK (status IN ('PENDING_CONFIRMATION','CONFIRMED','PREPARING','READY','DELIVERED','CANCELLED')),
      
      payment_status TEXT NOT NULL DEFAULT 'PAID'
        CHECK (payment_status IN ('PENDING','PAID','FAILED','REFUNDED')),
      
      payment_method TEXT NOT NULL DEFAULT 'CASH'
        CHECK (payment_method IN ('TRANSFER','CASH','ONLINE')),
      
      delivery_method TEXT NOT NULL DEFAULT 'PICKUP'
        CHECK (delivery_method IN ('PICKUP','DELIVERY')),
      
      subtotal_clp INT NOT NULL DEFAULT 0,
      delivery_fee_clp INT NOT NULL DEFAULT 0,
      total_clp INT NOT NULL DEFAULT 0,
      
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,

    // Tabla: order_items
    `CREATE TABLE IF NOT EXISTS order_items (
      id UUID PRIMARY KEY,
      order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
      product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
      
      product_name_snapshot TEXT NOT NULL,
      unit_price_clp INT NOT NULL,
      qty INT NOT NULL CHECK (qty > 0),
      line_total_clp INT NOT NULL,
      
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,

    // Tabla: product_images
    `CREATE TABLE IF NOT EXISTS product_images (
      id UUID PRIMARY KEY,
      product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
      url_original TEXT NOT NULL,
      url_large TEXT NOT NULL,
      url_thumb TEXT NOT NULL,
      sort_order INT NOT NULL DEFAULT 0,
      is_primary BOOLEAN NOT NULL DEFAULT false,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,

    // ============================================
    // COLUMNAS FALTANTES (ADD IF NOT EXISTS)
    // ============================================

    // customers
    `ALTER TABLE customers ADD COLUMN IF NOT EXISTS address TEXT;`,
    `ALTER TABLE customers ADD COLUMN IF NOT EXISTS notes TEXT;`,
    `ALTER TABLE customers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,
    `ALTER TABLE customers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,

    // orders
    `ALTER TABLE orders ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,
    `ALTER TABLE orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,

    // order_items
    `ALTER TABLE order_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,

    // users
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,

    // products
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,

    // ============================================
    // ÍNDICES
    // ============================================

    // Users
    `CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);`,
    `CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);`,
    `CREATE INDEX IF NOT EXISTS idx_users_is_active ON users(is_active);`,

    // Products
    `CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);`,
    `CREATE INDEX IF NOT EXISTS idx_products_is_active ON products(is_active);`,
    `CREATE INDEX IF NOT EXISTS idx_products_created_at ON products(created_at);`,

    // Product Images
    `CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON product_images(product_id);`,
    `CREATE INDEX IF NOT EXISTS idx_product_images_primary ON product_images(product_id, is_primary);`,

    // Customers - índice parcial para email (permite múltiples NULL)
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_email_unique ON customers(email) WHERE email IS NOT NULL;`,

    // Orders
    `CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);`,
    `CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);`,
    `CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);`,
    `CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON orders(payment_status);`,

    // Order Items
    `CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);`,
    `CREATE INDEX IF NOT EXISTS idx_order_items_product ON order_items(product_id);`,

    // ============================================
    // TRIGGERS updated_at
    // ============================================

    // Función para actualizar updated_at (compatible PostgreSQL 10)
    `CREATE OR REPLACE FUNCTION set_updated_at()
    RETURNS trigger AS $$
    BEGIN
      NEW.updated_at = NOW();
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;`,

    // Trigger: users
    `DROP TRIGGER IF EXISTS trg_users_updated_at ON users;`,
    `CREATE TRIGGER trg_users_updated_at
      BEFORE UPDATE ON users
      FOR EACH ROW EXECUTE PROCEDURE set_updated_at();`,

    // Trigger: products
    `DROP TRIGGER IF EXISTS trg_products_updated_at ON products;`,
    `CREATE TRIGGER trg_products_updated_at
      BEFORE UPDATE ON products
      FOR EACH ROW EXECUTE PROCEDURE set_updated_at();`,

    // Trigger: customers
    `DROP TRIGGER IF EXISTS trg_customers_updated_at ON customers;`,
    `CREATE TRIGGER trg_customers_updated_at
      BEFORE UPDATE ON customers
      FOR EACH ROW EXECUTE PROCEDURE set_updated_at();`,

    // Trigger: orders
    `DROP TRIGGER IF EXISTS trg_orders_updated_at ON orders;`,
    `CREATE TRIGGER trg_orders_updated_at
      BEFORE UPDATE ON orders
      FOR EACH ROW EXECUTE PROCEDURE set_updated_at();`,

    // ============================================
    // FIX: UNIQUE constraint en customers.email
    // ============================================

    // Eliminar constraint viejo si existe (permite múltiples NULL)
    `DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'customers_email_key' AND conrelid = 'customers'::regclass
      ) THEN
        ALTER TABLE customers DROP CONSTRAINT customers_email_key;
      END IF;
    EXCEPTION
      WHEN undefined_table THEN NULL;
      WHEN undefined_object THEN NULL;
    END $$;`,
  ];

  try {
    await client.query("BEGIN");

    let successCount = 0;
    for (let i = 0; i < statements.length; i++) {
      const stmt = statements[i];
      try {
        await client.query(stmt);
        successCount++;
      } catch (stmtError) {
        // Algunos errores son esperables (ej: constraint ya eliminado)
        // Solo loguear, no fallar
        console.warn(`⚠️  Warning on statement ${i + 1}:`, stmtError.message);
      }
    }

    await client.query("COMMIT");
    
    console.log(`✅ Complete migration successful!`);
    console.log(`   - ${successCount}/${statements.length} statements executed`);
    console.log(`   - All tables created/updated`);
    console.log(`   - All indexes created`);
    console.log(`   - All triggers created`);
    
  } catch (error) {
    await client.query("ROLLBACK");
    console.error("❌ Migration failed:", error.message);
    throw error;
  } finally {
    client.release();
  }
}

module.exports = { runCompleteMigrations };
