/**
 * Complete Database Migration (Canonical Schema)
 * 
 * Ejecuta migraciones completas e idempotentes para:
 * - Crear todas las tablas si no existen
 * - Agregar columnas faltantes
 * - Crear índices
 * - Crear triggers updated_at
 * - Fix UNIQUE constraint en customers.email
 * 
 * Compatible con PostgreSQL 10.23
 * Seguro ejecutar múltiples veces (idempotente)
 */

const { getPool } = require("../db");

async function runCompleteMigrations() {
  const pool = getPool();
  const client = await pool.connect();

  console.log("🔄 Starting complete database migration...");

  const statements = [
    // Set search path
    `SET search_path TO public;`,

    // ============================================
    // TABLAS BASE
    // ============================================

    // Tabla: users
    `CREATE TABLE IF NOT EXISTS users (
      id UUID PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      full_name TEXT,
      role TEXT NOT NULL DEFAULT 'STAFF' CHECK (role IN ('SUPERADMIN','ADMIN','STAFF')),
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,

    // Tabla: products
    `CREATE TABLE IF NOT EXISTS products (
      id UUID PRIMARY KEY,
      name TEXT NOT NULL,
      slug TEXT NOT NULL UNIQUE,
      description TEXT,
      price_clp INT NOT NULL CHECK (price_clp >= 0),
      stock_qty INT NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,

    // Tabla: customers
    `CREATE TABLE IF NOT EXISTS customers (
      id UUID PRIMARY KEY,
      email TEXT,
      full_name TEXT NOT NULL,
      phone TEXT,
      address TEXT,
      notes TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,

    // Tabla: orders
    `CREATE TABLE IF NOT EXISTS orders (
      id UUID PRIMARY KEY,
      order_no BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
      customer_id UUID NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
      
      status TEXT NOT NULL DEFAULT 'DELIVERED'
        CHECK (status IN ('PENDING_CONFIRMATION','CONFIRMED','PREPARING','READY','DELIVERED','CANCELLED')),
      
      payment_status TEXT NOT NULL DEFAULT 'PAID'
        CHECK (payment_status IN ('PENDING','PAID','FAILED','REFUNDED')),
      
      payment_method TEXT NOT NULL DEFAULT 'CASH'
        CHECK (payment_method IN ('TRANSFER','CASH','ONLINE')),
      
      delivery_method TEXT NOT NULL DEFAULT 'PICKUP'
        CHECK (delivery_method IN ('PICKUP','DELIVERY')),
      
      subtotal_clp INT NOT NULL DEFAULT 0,
      delivery_fee_clp INT NOT NULL DEFAULT 0,
      total_clp INT NOT NULL DEFAULT 0,
      
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,

    // Tabla: order_items
    `CREATE TABLE IF NOT EXISTS order_items (
      id UUID PRIMARY KEY,
      order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
      product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
      
      product_name_snapshot TEXT NOT NULL,
      unit_price_clp INT NOT NULL,
      qty INT NOT NULL CHECK (qty > 0),
      line_total_clp INT NOT NULL,
      
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,

    // Tabla: product_images
    `CREATE TABLE IF NOT EXISTS product_images (
      id UUID PRIMARY KEY,
      product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
      url_original TEXT NOT NULL,
      url_large TEXT NOT NULL,
      url_thumb TEXT NOT NULL,
      sort_order INT NOT NULL DEFAULT 0,
      is_primary BOOLEAN NOT NULL DEFAULT false,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,

    // ============================================
    // COLUMNAS FALTANTES (ADD IF NOT EXISTS)
    // ============================================

    // customers
    `ALTER TABLE customers ADD COLUMN IF NOT EXISTS address TEXT;`,
    `ALTER TABLE customers ADD COLUMN IF NOT EXISTS notes TEXT;`,
    `ALTER TABLE customers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,
    `ALTER TABLE customers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,

    // orders
    `ALTER TABLE orders ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,
    `ALTER TABLE orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,

    // order_items
    `ALTER TABLE order_items ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,

    // users
    `ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,

    // products
    `ALTER TABLE products ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();`,

    // ============================================
    // ÍNDICES
    // ============================================

    // Users
    `CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);`,
    `CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);`,
    `CREATE INDEX IF NOT EXISTS idx_users_is_active ON users(is_active);`,

    // Products
    `CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);`,
    `CREATE INDEX IF NOT EXISTS idx_products_is_active ON products(is_active);`,
    `CREATE INDEX IF NOT EXISTS idx_products_created_at ON products(created_at);`,

    // Product Images
    `CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON product_images(product_id);`,
    `CREATE INDEX IF NOT EXISTS idx_product_images_primary ON product_images(product_id, is_primary);`,

    // Customers - índice parcial para email (permite múltiples NULL)
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_email_unique ON customers(email) WHERE email IS NOT NULL;`,

    // Orders
    `CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);`,
    `CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);`,
    `CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);`,
    `CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON orders(payment_status);`,

    // Order Items
    `CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);`,
    `CREATE INDEX IF NOT EXISTS idx_order_items_product ON order_items(product_id);`,

    // ============================================
    // TRIGGERS updated_at
    // ============================================

    // Función para actualizar updated_at (compatible PostgreSQL 10)
    `CREATE OR REPLACE FUNCTION set_updated_at()
    RETURNS trigger AS $$
    BEGIN
      NEW.updated_at = NOW();
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;`,

    // Trigger: users
    `DROP TRIGGER IF EXISTS trg_users_updated_at ON users;`,
    `CREATE TRIGGER trg_users_updated_at
      BEFORE UPDATE ON users
      FOR EACH ROW EXECUTE PROCEDURE set_updated_at();`,

    // Trigger: products
    `DROP TRIGGER IF EXISTS trg_products_updated_at ON products;`,
    `CREATE TRIGGER trg_products_updated_at
      BEFORE UPDATE ON products
      FOR EACH ROW EXECUTE PROCEDURE set_updated_at();`,

    // Trigger: customers
    `DROP TRIGGER IF EXISTS trg_customers_updated_at ON customers;`,
    `CREATE TRIGGER trg_customers_updated_at
      BEFORE UPDATE ON customers
      FOR EACH ROW EXECUTE PROCEDURE set_updated_at();`,

    // Trigger: orders
    `DROP TRIGGER IF EXISTS trg_orders_updated_at ON orders;`,
    `CREATE TRIGGER trg_orders_updated_at
      BEFORE UPDATE ON orders
      FOR EACH ROW EXECUTE PROCEDURE set_updated_at();`,

    // ============================================
    // Tabla: product_variants
    // ============================================
    `CREATE TABLE IF NOT EXISTS product_variants (
      id UUID PRIMARY KEY,
      product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
      name VARCHAR(100) NOT NULL,
      price_override_clp INT,
      stock_qty INT NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
      is_active BOOLEAN NOT NULL DEFAULT true,
      sort_order INT NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,
    `CREATE INDEX IF NOT EXISTS idx_product_variants_product_id ON product_variants(product_id);`,
    `DROP TRIGGER IF EXISTS trg_product_variants_updated_at ON product_variants;`,
    `CREATE TRIGGER trg_product_variants_updated_at
      BEFORE UPDATE ON product_variants
      FOR EACH ROW EXECUTE PROCEDURE set_updated_at();`,

    // ============================================
    // Tabla: supplies (insumos)
    // ============================================
    `CREATE TABLE IF NOT EXISTS supplies (
      id UUID PRIMARY KEY,
      name VARCHAR(200) NOT NULL,
      unit VARCHAR(50),
      last_price_clp INT,
      last_updated TIMESTAMPTZ,
      notes TEXT,
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,
    `CREATE INDEX IF NOT EXISTS idx_supplies_name ON supplies(name);`,
    `DROP TRIGGER IF EXISTS trg_supplies_updated_at ON supplies;`,
    `CREATE TRIGGER trg_supplies_updated_at
      BEFORE UPDATE ON supplies
      FOR EACH ROW EXECUTE PROCEDURE set_updated_at();`,

    // ============================================
    // Tabla: expense_records (gastos)
    // ============================================
    `CREATE TABLE IF NOT EXISTS expense_records (
      id UUID PRIMARY KEY,
      supply_id UUID REFERENCES supplies(id) ON DELETE SET NULL,
      description VARCHAR(300) NOT NULL,
      amount_clp INT NOT NULL CHECK (amount_clp > 0),
      expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
      notes TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,
    `CREATE INDEX IF NOT EXISTS idx_expense_records_date ON expense_records(expense_date);`,

    // ============================================
    // Tablas: cake builder
    // ============================================
    `CREATE TABLE IF NOT EXISTS cake_config_category (
      id UUID PRIMARY KEY,
      type VARCHAR(50) NOT NULL,
      label VARCHAR(100) NOT NULL,
      sort_order INT NOT NULL DEFAULT 0,
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,
    `CREATE TABLE IF NOT EXISTS cake_config_option (
      id UUID PRIMARY KEY,
      category_id UUID NOT NULL REFERENCES cake_config_category(id) ON DELETE CASCADE,
      label VARCHAR(100) NOT NULL,
      description VARCHAR(300),
      extra_price_clp INT NOT NULL DEFAULT 0,
      is_default BOOLEAN NOT NULL DEFAULT false,
      diameter_cm INT,
      is_active BOOLEAN NOT NULL DEFAULT true,
      sort_order INT NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,
    `CREATE INDEX IF NOT EXISTS idx_cake_config_option_category ON cake_config_option(category_id);`,
    `CREATE TABLE IF NOT EXISTS cake_orders (
      id UUID PRIMARY KEY,
      order_number VARCHAR(30) UNIQUE NOT NULL,
      customer_name VARCHAR(200) NOT NULL,
      customer_email VARCHAR(200),
      customer_phone VARCHAR(50),
      customer_address TEXT,
      size_option_id UUID REFERENCES cake_config_option(id),
      layers_option_id UUID REFERENCES cake_config_option(id),
      sponge_option_id UUID REFERENCES cake_config_option(id),
      filling_option_id UUID REFERENCES cake_config_option(id),
      decoration_option_id UUID REFERENCES cake_config_option(id),
      base_price_clp INT NOT NULL DEFAULT 0,
      extras_price_clp INT NOT NULL DEFAULT 0,
      total_price_clp INT NOT NULL DEFAULT 0,
      deposit_clp INT NOT NULL DEFAULT 0,
      notes TEXT,
      status VARCHAR(30) NOT NULL DEFAULT 'PENDING_PAYMENT',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,
    `CREATE INDEX IF NOT EXISTS idx_cake_orders_status ON cake_orders(status);`,

    // Seed categorías iniciales del cake builder (idempotente)
    `INSERT INTO cake_config_category (id, type, label, sort_order, is_active)
     VALUES
       ('00000000-0000-0000-0001-000000000001', 'SIZE',       'Tamaño',      1, true),
       ('00000000-0000-0000-0001-000000000002', 'LAYERS',     'Capas',       2, true),
       ('00000000-0000-0000-0001-000000000003', 'SPONGE',     'Bizcocho',    3, true),
       ('00000000-0000-0000-0001-000000000004', 'FILLING',    'Relleno',     4, true),
       ('00000000-0000-0000-0001-000000000005', 'DECORATION', 'Decoración',  5, true)
     ON CONFLICT (id) DO NOTHING;`,

    // Seed opciones iniciales (idempotente)
    `INSERT INTO cake_config_option (id, category_id, label, extra_price_clp, is_default, diameter_cm, sort_order)
     VALUES
       ('00000000-0000-0000-0002-000000000001', '00000000-0000-0000-0001-000000000001', '10 pulgadas',   0,     true,  25, 1),
       ('00000000-0000-0000-0002-000000000002', '00000000-0000-0000-0001-000000000001', '16 pulgadas',   15000, false, 40, 2),
       ('00000000-0000-0000-0002-000000000003', '00000000-0000-0000-0001-000000000001', '20 pulgadas',   25000, false, 50, 3),
       ('00000000-0000-0000-0002-000000000004', '00000000-0000-0000-0001-000000000001', '24 pulgadas',   35000, false, 60, 4),
       ('00000000-0000-0000-0002-000000000005', '00000000-0000-0000-0001-000000000002', '1 capa',        0,     true,  null, 1),
       ('00000000-0000-0000-0002-000000000006', '00000000-0000-0000-0001-000000000002', '2 capas',       8000,  false, null, 2),
       ('00000000-0000-0000-0002-000000000007', '00000000-0000-0000-0001-000000000002', '3 capas',       15000, false, null, 3),
       ('00000000-0000-0000-0002-000000000008', '00000000-0000-0000-0001-000000000003', 'Vainilla',      0,     true,  null, 1),
       ('00000000-0000-0000-0002-000000000009', '00000000-0000-0000-0001-000000000003', 'Chocolate',     3000,  false, null, 2),
       ('00000000-0000-0000-0002-000000000010', '00000000-0000-0000-0001-000000000003', 'Red Velvet',    5000,  false, null, 3),
       ('00000000-0000-0000-0002-000000000011', '00000000-0000-0000-0001-000000000004', 'Manjar',        0,     true,  null, 1),
       ('00000000-0000-0000-0002-000000000012', '00000000-0000-0000-0001-000000000004', 'Ganash chocolate', 4000, false, null, 2),
       ('00000000-0000-0000-0002-000000000013', '00000000-0000-0000-0001-000000000004', 'Crema Bariloche', 4000, false, null, 3),
       ('00000000-0000-0000-0002-000000000014', '00000000-0000-0000-0001-000000000005', 'Decoración estándar', 0, true, null, 1),
       ('00000000-0000-0000-0002-000000000015', '00000000-0000-0000-0001-000000000005', 'Decoración temática', 10000, false, null, 2)
     ON CONFLICT (id) DO NOTHING;`,

    // ============================================
    // FEATURE: Product Toppings
    // ============================================
    `CREATE TABLE IF NOT EXISTS product_toppings (
      id UUID PRIMARY KEY,
      product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
      name VARCHAR(100) NOT NULL,
      type VARCHAR(20) NOT NULL DEFAULT 'ADDITIONAL' CHECK (type IN ('BASE', 'ADDITIONAL')),
      price_clp INT NOT NULL DEFAULT 0 CHECK (price_clp >= 0),
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,
    `CREATE INDEX IF NOT EXISTS idx_product_toppings_product_id ON product_toppings(product_id);`,
    `DROP TRIGGER IF EXISTS trg_product_toppings_updated_at ON product_toppings;`,
    `CREATE TRIGGER trg_product_toppings_updated_at
      BEFORE UPDATE ON product_toppings
      FOR EACH ROW EXECUTE PROCEDURE set_updated_at();`,

    // ============================================
    // FEATURE: System Config (for global settings like cake_base_price)
    // ============================================
    `CREATE TABLE IF NOT EXISTS system_config (
      key VARCHAR(100) PRIMARY KEY,
      value TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,
    // Seed default cake base price
    `INSERT INTO system_config (key, value) VALUES ('cake_base_price', '30000') ON CONFLICT (key) DO NOTHING;`,

    // ============================================
    // FEATURE: Order Items Enhancements (variants & toppings)
    // ============================================
    `ALTER TABLE order_items ADD COLUMN IF NOT EXISTS variant_id UUID REFERENCES product_variants(id) ON DELETE SET NULL;`,
    `ALTER TABLE order_items ADD COLUMN IF NOT EXISTS variant_name VARCHAR(100);`,
    `ALTER TABLE order_items ADD COLUMN IF NOT EXISTS selected_toppings JSONB;`,

    // ============================================
    // FEATURE: Automatic Stock Calculation (Trigger)
    // ============================================
    `CREATE OR REPLACE FUNCTION update_product_stock_from_variants()
    RETURNS TRIGGER AS $$
    BEGIN
      UPDATE products
      SET stock_qty = (
        SELECT COALESCE(SUM(stock_qty), 0)
        FROM product_variants
        WHERE product_id = COALESCE(NEW.product_id, OLD.product_id)
      )
      WHERE id = COALESCE(NEW.product_id, OLD.product_id);
      RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;`,

    `DROP TRIGGER IF EXISTS trg_update_stock_variants_insert_update ON product_variants;`,
    `CREATE TRIGGER trg_update_stock_variants_insert_update
      AFTER INSERT OR UPDATE OF stock_qty, product_id ON product_variants
      FOR EACH ROW EXECUTE PROCEDURE update_product_stock_from_variants();`,

    `DROP TRIGGER IF EXISTS trg_update_stock_variants_delete ON product_variants;`,
    `CREATE TRIGGER trg_update_stock_variants_delete
      AFTER DELETE ON product_variants
      FOR EACH ROW EXECUTE PROCEDURE update_product_stock_from_variants();`,


    // ============================================
    // FEATURE: Hero Slides (Dynamic Carousel)
    // ============================================
    `CREATE TABLE IF NOT EXISTS hero_slides (
      id UUID PRIMARY KEY,
      title VARCHAR(200),
      subtitle VARCHAR(300),
      button_text VARCHAR(100),
      button_link VARCHAR(300),
      image_url VARCHAR(500) NOT NULL,
      is_active BOOLEAN NOT NULL DEFAULT true,
      sort_order INT NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );`,
    `CREATE INDEX IF NOT EXISTS idx_hero_slides_active_sort ON hero_slides(is_active, sort_order);`,
    `DROP TRIGGER IF EXISTS trg_hero_slides_updated_at ON hero_slides;`,
    `CREATE TRIGGER trg_hero_slides_updated_at
      BEFORE UPDATE ON hero_slides
      FOR EACH ROW EXECUTE PROCEDURE set_updated_at();`,

    // ============================================
    // FIX: Agregar order_code a orders si no existe
    // ============================================
    `DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name='orders' AND column_name='order_code'
      ) THEN
        ALTER TABLE orders ADD COLUMN order_code TEXT;
      END IF;
    EXCEPTION WHEN undefined_table THEN NULL;
    END $$;`,

    // ============================================
    // FEATURE: Order Price Adjustments
    // ============================================
    `ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_amount_clp INT NOT NULL DEFAULT 0;`,
    `ALTER TABLE orders ADD COLUMN IF NOT EXISTS final_price_override_clp INT;`,

    // ============================================
    // FIX: orders.status constraint — incluir PENDING_PAYMENT
    // ============================================
    `ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_status_check;`,
    `DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'orders_status_check_v2' AND conrelid = 'orders'::regclass
      ) THEN
        ALTER TABLE orders ADD CONSTRAINT orders_status_check_v2
          CHECK (status IN ('PENDING_PAYMENT','PENDING_CONFIRMATION','CONFIRMED','PAID','PREPARING','READY','DELIVERED','CANCELLED'));
      END IF;
    EXCEPTION WHEN undefined_table THEN NULL;
    END $$;`,

    // ============================================
    // FIX: UNIQUE constraint en customers.email
    // ============================================

    // Eliminar constraint viejo si existe (permite múltiples NULL)
    `DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'customers_email_key' AND conrelid = 'customers'::regclass
      ) THEN
        ALTER TABLE customers DROP CONSTRAINT customers_email_key;
      END IF;
    EXCEPTION
      WHEN undefined_table THEN NULL;
      WHEN undefined_object THEN NULL;
    END $$;`,
  ];

  try {
    await client.query("BEGIN");

    let successCount = 0;
    for (let i = 0; i < statements.length; i++) {
      const stmt = statements[i];
      const sp = `sp_mig_${i}`;
      try {
        await client.query(`SAVEPOINT ${sp}`);
        await client.query(stmt);
        await client.query(`RELEASE SAVEPOINT ${sp}`);
        successCount++;
      } catch (stmtError) {
        // Rollback al savepoint para no abortar la transacción completa
        await client.query(`ROLLBACK TO SAVEPOINT ${sp}`);
        console.warn(`⚠️  Warning on statement ${i + 1}:`, stmtError.message);
      }
    }

    await client.query("COMMIT");
    
    console.log(`✅ Complete migration successful!`);
    console.log(`   - ${successCount}/${statements.length} statements executed`);
    console.log(`   - All tables created/updated`);
    console.log(`   - All indexes created`);
    console.log(`   - All triggers created`);
    
  } catch (error) {
    await client.query("ROLLBACK");
    console.error("❌ Migration failed:", error.message);
    throw error;
  } finally {
    client.release();
  }
}

module.exports = { runCompleteMigrations };
